<a href="https://colab.research.google.com/github/Debasmita-Halder/tutorial-1/blob/main/DataMiningTitanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
file1=r"/content/drive/MyDrive/dataset (2).csv"
file2=r"/content/drive/MyDrive/train1 (1).csv"
df=pd.read_csv(file1)
df1=pd.read_csv(file2)
print(df.head(10))
print(df1.head(10))
df.describe()
df1.describe()
df.shape
df.columns
df.dtypes
pclass23=df1[df1["Pclass"].isin([2,3])]
pclass23.head()
agenonull=df1[df1["Age"].notna()]
agenonull.head()
anames=df1.loc[df1["Age"]>35,"Name"]
anames.head()
df1.iloc[9:25,1:8]
a1=(df1.iloc[0:3,3]=="anonymous")
print(a1)
print("MEAN AGE OF PASSENGER ON BOARD",df1["Age"].mean())
print("MEDIAN VALUE OF PASSENGER AGE AND FARE ON BOARD",df1[["Age","Fare"]].median())
df1[["Age","Fare"]].describe()
df1[["Age","Sex"]].groupby("Sex").mean()
df1[["Age","Fare"]].describe()
df1[["Age","Sex"]].groupby("Sex").max()
df1[["Age","Sex"]].groupby("Sex").min()
df1[["Age","Sex"]].groupby("Sex").first()
df1.groupby(["Sex","Pclass"])["Fare"].mean()
df1.groupby("Sex")["Age"].mean()
df1["Pclass"].value_counts()
df1.groupby("Pclass")["Pclass"].count()
df1.sort_values(by="Age",ascending=True).head()
df1.sort_values(by=["Pclass","Age"],ascending=False).head()
df1["Name"].str.lower()
print(df1.head())
df1["Name"].str.split(",")
df1["surname"]=df1["Name"].str.split(",").str.get(1)
print("SURNAME OF THE PASSENGER",df1["surname"])
df1["RealName"]=df1["Name"].str.split(",").str.get(0)
print("REAL NAME OF THE PASSENGER",df1["RealName"])
df1["Salutions"]=df1["surname"].str.split(",").str.get(0)
df1.head()
df1["Salutions"]=df1["surname"].str.split(",").str.get(1)
df1.head()
df1["Name"].str.contains("Mr")
df1["Name"].str.contains("Miss")
df1[df1["Name"].str.contains("Countess")]
df1["Name"].str.len()
df1.loc[df1["Name"].str.len().idxmax(),"Name"]
df1["SHORTGENDER"]=df1["Sex"].replace({"male":"M","female":"F"})
df1.head()
print(df1["SHORTGENDER"])
df1.corr()

  Customer ID Purchase Date Product ID  Price  Discount
0        C001      1/1/2022       P001    100        10
1        C002      1/2/2022       P002    150        15
2        C003      1/3/2022       P003    200        20
3        C004      1/4/2022       P001    100        10
4        C005      1/5/2022       P002    150        15
5        C006      1/6/2022       P003    200        20
6        C007      1/7/2022       P004     75         5
7        C008      1/8/2022       P005    125        10
8        C009      1/9/2022       P006    300        30
9        C010     1/10/2022       P001    100        10
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3
5            6         0       3
6            7         0       1
7            8         0       3
8            9         1       3
9           10         1       2

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0
5                                   Moran, Mr. James    male   NaN      0
6                            McCarthy, Mr. Timothy J    male  54.0      0
7                     Palsson, Master. Gosta Leonard    male   2.0      3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
5      0            330877   8.4583   NaN        Q
6      0             17463  51.8625   E46        S
7      1            349909  21.0750   NaN        S
8      2            347742  11.1333   NaN        S
9      0            237736  30.0708   NaN        C
0    False
1    False
2    False
Name: Name, dtype: bool
MEAN AGE OF PASSENGER ON BOARD 29.69911764705882
MEDIAN VALUE OF PASSENGER AGE AND FARE ON BOARD Age     28.0000
Fare    14.4542
dtype: float64
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
SURNAME OF THE PASSENGER 0                                  Mr. Owen Harris
1       Mrs. John Bradley (Florence Briggs Thayer)
2                                      Miss. Laina
3               Mrs. Jacques Heath (Lily May Peel)
4                                Mr. William Henry
                          ...
886                                    Rev. Juozas
887                           Miss. Margaret Edith
888                 Miss. Catherine Helen "Carrie"
889                                Mr. Karl Howell
890                                    Mr. Patrick
Name: surname, Length: 891, dtype: object
REAL NAME OF THE PASSENGER 0         Braund
1        Cumings
2      Heikkinen
3       Futrelle
4          Allen
         ...
886     Montvila
887       Graham
888     Johnston
889         Behr
890       Dooley
Name: RealName, Length: 891, dtype: object
0      M
1      F
2      F
3      F
4      M
      ..
886    M
887    F
888    F
889    M
890    M
Name: SHORTGENDER, Length: 891, dtype: object

<ipython-input-6-8fda0028bcd2>:54: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df1.corr()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Salutions
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658,NaN
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307,NaN
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500,NaN
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067,NaN
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651,NaN
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225,NaN
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000,NaN
Salutions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN